# Generated by Django 6.0.4 on 2026-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_administrator_is_owner_delete_employee'),
        ('bookings', '0007_alter_booking_options_and_more'),
        ('hotels', '0008_roomcategory_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_published_at_required',
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('P', 'Опубликован'), ('D', 'Черновик'), ('M', 'Ожидает проверки'), ('R', 'Не прошел модерацию'), ('A', 'Убран из публичного доступа')], default='D', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='bookingpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', False), ('status', 'C')), models.Q(('status', 'C'), _negated=True), _connector='OR'), name='booking_payment_paid_at_required', violation_error_message='При закрытии платежанеобходимо указать дату оплаты'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status__in', ['P', 'A'])), models.Q(('status__in', ['P', 'A']), _negated=True), _connector='OR'), name='review_published_at_required', violation_error_message='Необходимо указать дату публикации'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_check_out_after_check_in',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='booking_check_out_after_check_in', violation_error_message='Дата выселения должна быть позже даты заселения'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_moved_to_required',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moved_to__isnull', False), ('status', 'M')), models.Q(('status', 'M'), _negated=True), _connector='OR'), name='booking_moved_to_required', violation_error_message='При переносе бронированиянеобходимо указать ссылку на новое'),
        ),
    ]
