# Generated by Django 6.0.4 on 2026-05-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingpayment',
            name='booking_payment_paid_at_required',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
        migrations.DeleteModel(
            name='BookingPayment',
        ),
    ]
